### ISSUE TITLE
Add support for maps? 

### ISSUE THREAD

**Issue by seivan** [tony612/google-protos#2]
```
syntax = "proto3";

message Sample {
  map<int32, int32> name = 1;
}
```
gives

```
$ protoc --elixir_out=./lib sample.proto      

** (ArgumentError) argument error
    :erlang.byte_size(nil)
    lib/protobuf/protoc/generator/util.ex:27: Protobuf.Protoc.Generator.Util.trans_type_name/2
    lib/protobuf/protoc/generator/message.ex:179: anonymous fn/4 in Protobuf.Protoc.Generator.Message.nested_maps/2
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    lib/protobuf/protoc/generator/message.ex:135: Protobuf.Protoc.Generator.Message.get_fields/2
    lib/protobuf/protoc/generator/message.ex:18: Protobuf.Protoc.Generator.Message.parse_desc/2
    lib/protobuf/protoc/generator/message.ex:11: Protobuf.Protoc.Generator.Message.generate/2
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
--elixir_out: protoc-gen-elixir: Plugin failed with status code 1.

```

**Comment by tony612** [comment]
I think it's an issue of https://github.com/tony612/protobuf-elixir. Could you open an issue there?

**Comment by seivan** [comment]
@tony612 I think it's the parser to exporting .ex files. Shouldn't that be here?

**Comment by seivan** [comment]
Thanks!
